; Development configuration 

[DB]
dbtype = mysql
dbhost = 127.0.0.1
dbname = prwb_2526_c06
dbuser = root
dbpassword = root
mysql_path = "C:\PRW2526\tools\xampp\mysql\bin\"
;mysql_path = "/Applications/XAMPP/xamppfiles/bin/" ; pour macOS

[Controllers]
default_controller = user

[Web]
web_root = "/prwb_2526_c06/"

[Sanitization]
;insafe_inputs[] = markdown_body
;insafe_inputs[] = boards

[Rules]

[text]
TITLE_MIN_LENGTH = 3
TITLE_MAX_LENGHT = 255
DESCR_MIN_LENGHT = 3

[IMG.upload]
UPLOAD_MAX_FILESIZE=5242880

MAX_IMG_WIDTH=1080
MAX_IMG_HEIGHT=1080
MAX_THUMB_WIDTH=360
MAX_THUMB_HEIGHT=360

