; Development configuration 

[DB]
dbtype = mysql
dbhost = 127.0.0.1
dbname = prwb_2526_c06
dbuser = root
dbpassword = root
mysql_path = "C:\PRW2526\tools\xampp\mysql\bin\"
;mysql_path = "/Applications/XAMPP/xamppfiles/bin/" ; pour macOS

[Controllers]
default_controller = user

[Web]
web_root = "/prwb_2526_c06/"

[Sanitization]
;insafe_inputs[] = markdown_body
;insafe_inputs[] = boards

[Rules]

[text]
TITLE_MIN_LENGTH = 3
TITLE_MAX_LENGTH = 255
DESCR_MIN_LENGTH = 3

[item]
DURATION_MIN = 1
DURATION_MAX = 365
PRICE_MIN = 0.01

[IMG.upload]
UPLOAD_MAX_FILESIZE=5242880

MAX_IMG_WIDTH=1080
MAX_IMG_HEIGHT=1080
MAX_THUMB_WIDTH=360
MAX_THUMB_HEIGHT=360

...
[JavaScript]
disable_js = false
; les chemins actifs malgré la désactivation de JS
; Chemins relatifs locaux
;enabled_paths[] = "css/bootstrap-5.3.3-dist/js/bootstrap.min.js"
;enabled_paths[] = "lib/popper.min.js"
; URLs CDN
enabled_paths[] = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
enabled_paths[] = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"
...
